services:
  api:
    build: .
    ports:
      - "${PORT:-5005}:5005"
    env_file:
      - .env
    environment:
      - PORT=5005
      - HOST=0.0.0.0
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py
    restart: always

networks:
  default:
    name: docapture-network
